version: '3.5'

services: 
    lb:
      image: nginx
      container_name: nginx_loadbalancer
      ports:
        - "8081:8081"
      networks:
        - frontend
      volumes: 
        - ./nginx/http.conf:/etc/nginx/nginx.conf
      restart: always
      depends_on:
        - api1
        - api2
        - api3
    redis:
      image: redis:alpine
      hostname: redis
      container_name: redis_cache
      ports:
        - "6379:6379"
      networks:
        - backend
      volumes:
        - redis_data:/data/redis
      restart: always
    api1:
      image: pickezdocker/inditeminds-api:1.0.0
      hostname: api1
      container_name: api_primary
      networks:
        - frontend
        - backend
      environment: 
            - PORT=5555
            - NODE_ENV="production"
            - MONGODB_PROD_URI=mongodb+srv://pick_user35:reverseit40252@cluster0.zecxk.mongodb.net/inditeminds_api_prod?retryWrites=true&w=majority
            - JWT_ACC_TOKEN_SECRET=ihavenoidea44205
            - JWT_ACC_TOKEN_VALID_UNTIL=20m
            - JWT_REF_TOKEN_SECRET=ihaveidea50244
            - JWT_REF_TOKEN_VALID_UNTIL=1d
            - REDIS_HOST=redis
      restart: always
      depends_on:
        - redis
    api2:
      image: pickezdocker/inditeminds-api:1.0.0
      hostname: api2
      container_name: api_first_backup
      networks:
        - frontend
        - backend
      environment: 
            - PORT=7777
            - NODE_ENV="production"
            - MONGODB_PROD_URI=mongodb+srv://pick_user35:reverseit40252@cluster0.zecxk.mongodb.net/inditeminds_api_prod?retryWrites=true&w=majority
            - JWT_ACC_TOKEN_SECRET=ihavenoidea44205
            - JWT_ACC_TOKEN_VALID_UNTIL=20m
            - JWT_REF_TOKEN_SECRET=ihaveidea50244
            - JWT_REF_TOKEN_VALID_UNTIL=1d
            - REDIS_HOST=redis
      restart: always
      depends_on:
        - redis
    api3:
      image: pickezdocker/inditeminds-api:1.0.0
      hostname: api3
      container_name: api_second_backup
      networks:
        - frontend
        - backend
      environment: 
            - PORT=8888
            - NODE_ENV="production"
            - MONGODB_PROD_URI=mongodb+srv://pick_user35:reverseit40252@cluster0.zecxk.mongodb.net/inditeminds_api_prod?retryWrites=true&w=majority
            - JWT_ACC_TOKEN_SECRET=ihavenoidea44205
            - JWT_ACC_TOKEN_VALID_UNTIL=20m
            - JWT_REF_TOKEN_SECRET=ihaveidea50244
            - JWT_REF_TOKEN_VALID_UNTIL=1d
            - REDIS_HOST=redis
      restart: always
      depends_on:
        - redis
volumes:
  redis_data:
networks:
  frontend:
  backend:

  

